name: sig_proyecto
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  http: ^0.13.5  
  flutter_secure_storage: ^8.0.0
  intl: ^0.17.0
  geolocator: ^8.0.0
  shared_preferences: ^2.0.8
  xml: ^6.1.0
  google_maps_flutter: ^2.10.0
  image_picker: ^0.8.6

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/utils/sidebar_fondo.jpg
    - assets/utils/splash.png
    - assets/utils/GestionAsis.jpg
    - assets/utils/image.png
    - assets/utils/grijo.jpg 
    - assets/utils/login.png
    - assets/utils/logo.png
    - assets/utils/start.png
    - assets/utils/end.png
    - assets/utils/intermediate.png
    


